CANVAS_WIDTH = 650
CANVAS_HEIGHT = 450
PADDLE_LENGTH = 30
PADDLE_THICKNESS = 15
PADDING = PADDLE_THICKNESS * 2
BALL_SIZE = 15
REFLECTION_ANGLE = 45
# マルチ対戦用
CANVAS_WIDTH_MULTI = 650
CANVAS_HEIGHT_MULTI = 650
CORNER_BLOCK_THICKNESS = 15
CORNER_BLOCK_SIZE = PADDLE_THICKNESS * 8
