# Generated by Django 4.2 on 2024-08-07 04:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import players.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/uploads/avatar/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), players.models.validate_image], verbose_name='アバター')),
                ('level', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='レベル')),
                ('play_count', models.IntegerField(default=0, verbose_name='総試合数')),
                ('win_count', models.IntegerField(default=0, verbose_name='勝った試合数')),
                ('id_42', models.CharField(blank=True, max_length=20, null=True, verbose_name='42 Intra ID')),
                ('link_42', models.CharField(blank=True, max_length=255, null=True, verbose_name='42 Intra link')),
                ('lang', models.CharField(choices=[('en', '英語'), ('ja', '日本語'), ('fr', 'フランス語')], default='en', max_length=10, verbose_name='言語設定')),
                ('data_created', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('status', models.CharField(choices=[('friend_match', 'フレンドマッチ中'), ('lounge_match', 'ラウンジマッチ中'), ('tournament_match', 'トーナメントマッチ中'), ('tournament_room', 'トーナメント控室'), ('tournament_prepare', 'トーナメント準備中'), ('tournament', 'トーナメント中'), ('friend_waiting', 'フレンドマッチ待機中'), ('lounge_waiting', 'ラウンジマッチ待機中'), ('waiting', '待機中')], default='waiting', max_length=20, verbose_name='ステータス')),
                ('online', models.BooleanField(blank=True, default=False, null=True, verbose_name='オンラインステータス')),
                ('current_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_players', to='game.match', verbose_name='現在のマッチ')),
                ('friends', models.ManyToManyField(blank=True, to='players.player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='プレイヤー')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='players.player')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_requests', to='players.player')),
            ],
        ),
    ]
