# Generated by Django 4.1 on 2024-06-10 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(blank=True, to='players.player'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='players.player')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_requests', to='players.player')),
            ],
        ),
    ]
