# Generated by Django 4.1 on 2024-06-25 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_friends_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/avatar/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='アバター'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id_42',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='42 Intra ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='link_42',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='42 Intra link'),
        ),
    ]
