# Generated by Django 4.2 on 2024-07-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_current_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('friend_match', 'フレンドマッチ中'), ('lounge_match', 'ラウンジマッチ中'), ('tournament_match', 'トーナメントマッチ中'), ('tournament_room', 'トーナメント控室'), ('tournament_prepare', 'トーナメント準備中'), ('tournament', 'トーナメント中'), ('friend_waiting', 'フレンドマッチ待機中'), ('lounge_waiting', 'ラウンジマッチ待機中'), ('waiting', '待機中')], default='waiting', max_length=20, verbose_name='ステータス'),
        ),
    ]
