# Generated by Django 4.1 on 2024-06-27 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_avatar_alter_player_id_42_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/avatar/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='アバター'),
        ),
    ]
