# Generated by Django 4.2 on 2024-07-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_status'),
        ('players', '0004_alter_player_online'),
    ]

    operations = [
    ]
