# Generated by Django 4.1 on 2024-06-28 18:33

import django.core.validators
from django.db import migrations, models
import players.models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_alter_player_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/avatar/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png']), players.models.validate_image], verbose_name='アバター'),
        ),
    ]
