# Generated by Django 4.2 on 2024-07-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_player_lang'),
        ('players', '0005_merge_20240710_0904'),
    ]

    operations = [
    ]
