FROM python:3.12 AS pong-server

RUN apt-get update && \
    apt-get install -y netcat-traditional postgresql-client && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN useradd -m django

COPY tools/requirements.txt .
RUN pip install -r requirements.txt

# COPY game-server /app/
COPY tools/docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# 環境変数を設定
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

USER django

CMD [ "python", "manage.py", "runserver", "0.0.0.0:8002" ]
ENTRYPOINT [ "/usr/local/bin/docker-entrypoint.sh" ]