# Generated by Django 4.1 on 2024-04-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='トーナメント名')),
                ('start', models.DateField(verbose_name='開始日')),
                ('period', models.DateField(verbose_name='締切')),
            ],
            options={
                'verbose_name': 'トーナメント',
            },
        ),
    ]
