# Generated by Django 4.2 on 2024-08-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='User.username', max_length=20, null=True, verbose_name='ニックネーム')),
            ],
            options={
                'verbose_name': 'エントリー',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(blank=True, default=-1, null=True, verbose_name='ラウンド')),
                ('game_name', models.CharField(choices=[('pong', 'Pong'), ('pong4', 'Pong4')], default='pong', max_length=20, verbose_name='ゲームタイプ')),
                ('status', models.CharField(choices=[('before', '対戦前'), ('ongoing', '対戦中'), ('after', '対戦後'), ('canceled', 'キャンセル')], default='before', max_length=10, verbose_name='status')),
                ('score1', models.IntegerField(blank=True, default=0, null=True, verbose_name='スコア(プレイヤー1)')),
                ('score2', models.IntegerField(blank=True, default=0, null=True, verbose_name='スコア(プレイヤー2)')),
                ('score3', models.IntegerField(blank=True, default=0, null=True, verbose_name='スコア(プレイヤー3)')),
                ('score4', models.IntegerField(blank=True, default=0, null=True, verbose_name='スコア(プレイヤー4)')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '対戦',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='トーナメント名')),
                ('start', models.DateTimeField(verbose_name='開始時間')),
                ('period', models.DateTimeField(verbose_name='エントリー締切')),
                ('max_participants', models.IntegerField(default=16, verbose_name='最大人数')),
                ('status', models.CharField(choices=[('upcoming', '開始前'), ('preparing', '準備中'), ('ongoing', '進行中'), ('finished', '終了'), ('canceled', 'キャンセル')], default='upcoming', max_length=10, verbose_name='状態')),
                ('current_round', models.IntegerField(default=1, verbose_name='ラウンド')),
                ('result_json', models.TextField(default='[]')),
            ],
            options={
                'verbose_name': 'トーナメント',
            },
        ),
    ]
