# Generated by Django 4.1 on 2024-06-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='User.username', max_length=20, null=True, verbose_name='ニックネーム')),
            ],
            options={
                'verbose_name': 'エントリー',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(blank=True, default=-1, null=True, verbose_name='ラウンド')),
                ('game_name', models.CharField(choices=[('pong', 'Pong'), ('pong4', 'Pong4')], default='pong', max_length=20, verbose_name='ゲームタイプ')),
                ('status', models.CharField(choices=[('before', '対戦前'), ('ongoing', '対戦中'), ('after', '対戦後')], default='before', max_length=10, verbose_name='status')),
                ('score1', models.IntegerField(blank=True, default=0, null=True, verbose_name='スコア(プレイヤー1)')),
                ('score2', models.IntegerField(blank=True, default=0, null=True, verbose_name='スコア(プレイヤー2)')),
                ('score3', models.IntegerField(blank=True, default=0, null=True, verbose_name='スコア(プレイヤー3)')),
                ('score4', models.IntegerField(blank=True, default=0, null=True, verbose_name='スコア(プレイヤー4)')),
            ],
            options={
                'verbose_name': '対戦',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='トーナメント名')),
                ('start', models.DateTimeField(verbose_name='開始時間')),
                ('period', models.DateTimeField(verbose_name='エントリー締切')),
            ],
            options={
                'verbose_name': 'トーナメント',
            },
        ),
    ]
