# Generated by Django 4.1 on 2024-06-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='トーナメント名'),
        ),
    ]
