# Generated by Django 4.1 on 2024-06-03 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='nickname',
            field=models.CharField(default='User.username', max_length=20, null=True, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player1', to='players.player', verbose_name='プレイヤー1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player2', to='players.player', verbose_name='プレイヤー2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.IntegerField(blank=True, default=-1, null=True, verbose_name='ラウンド'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='スコア(プレイヤー1)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='スコア(プレイヤー2)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('before', '対戦前'), ('ongoing', '対戦中'), ('after', '対戦後')], default='before', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.tournament', verbose_name='トーナメント'),
        ),
    ]
