# Generated by Django 4.1 on 2024-04-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='period',
            field=models.DateTimeField(verbose_name='エントリー締切'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start',
            field=models.DateTimeField(verbose_name='開始時間'),
        ),
    ]
