# Generated by Django 4.2 on 2024-08-07 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bye_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bye_tournaments', to='players.player', verbose_name='不戦勝'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='tournament_matches', to='game.match', verbose_name='全マッチ'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='second_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='players.player', verbose_name='2位'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='third_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third', to='players.player', verbose_name='3位'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='players.player', verbose_name='優勝'),
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player1', to='players.player', verbose_name='プレイヤー1'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player2', to='players.player', verbose_name='プレイヤー2'),
        ),
        migrations.AddField(
            model_name='match',
            name='player3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player3', to='players.player', verbose_name='プレイヤー3'),
        ),
        migrations.AddField(
            model_name='match',
            name='player4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_player4', to='players.player', verbose_name='プレイヤー4'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.tournament', verbose_name='トーナメント'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player'),
        ),
        migrations.AddField(
            model_name='entry',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
        migrations.AddField(
            model_name='entry',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tournament'),
        ),
    ]
