# Generated by Django 4.2 on 2024-07-09 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_status'),
        ('game', '0002_entry_player_match_player1_match_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bye_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bye_tournaments', to='players.player', verbose_name='不戦勝'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='current_round',
            field=models.IntegerField(default=1, verbose_name='ラウンド'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='matches',
            field=models.ManyToManyField(related_name='tournament_matches', to='game.match', verbose_name='全マッチ'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='second_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='players.player', verbose_name='2位'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='third_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third', to='players.player', verbose_name='3位'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='players.player', verbose_name='優勝'),
        ),
    ]
