# Generated by Django 4.1 on 2024-07-05 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_entry_player_match_player1_match_player2_and_more'),
        ('game', '0004_alter_tournament_name'),
    ]

    operations = [
    ]
