# Generated by Django 4.1 on 2024-07-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_tournament_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('upcoming', '開始前'), ('ongoing', '進行中'), ('finished', '終了')], default='upcoming', max_length=10, verbose_name='状態'),
        ),
    ]
