# Generated by Django 4.2 on 2024-07-07 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_merge_20240705_0021'),
        ('game', '0006_tournament_status'),
    ]

    operations = [
    ]
