# Generated by Django 4.2 on 2024-07-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_tournament_result_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('upcoming', '開始前'), ('preparing', '準備中'), ('ongoing', '進行中'), ('finished', '終了'), ('canceled', 'キャンセル')], default='upcoming', max_length=10, verbose_name='状態'),
        ),
    ]
