# Generated by Django 4.2 on 2024-07-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_tournament_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='tournament_matches', to='game.match', verbose_name='全マッチ'),
        ),
    ]
