# Generated by Django 4.2 on 2024-07-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_tournament_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('before', '対戦前'), ('ongoing', '対戦中'), ('after', '対戦後'), ('canceled', 'キャンセル')], default='before', max_length=10, verbose_name='status'),
        ),
    ]
