# Generated by Django 4.2 on 2024-07-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_match_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
