# Generated by Django 4.2 on 2024-08-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_match_status'),
        ('game', '0010_alter_match_last_updated'),
    ]

    operations = [
    ]
