'use strict';

export const labels_fr = {
	langCode: 'fr',
	langName: 'français',
    home: {
        title: '',
        labelUsername: '', 
        labelPassword: '', 
        labelButtonLogin: '',
        labelButtonLogout: '',
        textSignUp: '',
        labelLinkSignUp: '',
    },
    register: {
        title: '',
        labelUsername: '', 
        labelPassword: '', 
        labelPasswordConfirm: '', 
        descUsername: [''],
        descPassword: [''],
        descPasswordConfirm: '',
        labelButtonConfirm: '',
        textConfirm: '',
        labelButtonRegister: '',
        labelButtonBack: '',
        textComplete: '',
        labelButtonLogin: '',
    },
    formErrorMessages: {
        valueMissing: '',
        patternMismatch: '',
        tooLong: '',
        tooShort: '',
        passwordIsNotSame: '',
        isExists: '',
        loginError1: '',
        loginError2: '',
    },

    dashboard: {
        title: '',
    },
    friends: {
        title: '',
        labelMatch: '',
        labelReceiveMatch: '',
        labelCancel: '',
        labelRmFriend: '',
        labelAccept: '',
        labelDecline: '',
        labelApply: '',
        labelSearch: '',
        labelSendRequest: '',
        labelRequest: '',
        msgNoUsername: '',
        msgNoFriends: '',
        labelListFriends: '',
        labelReceivedRequest: '',
        labelRecommended: '',
        msgNoRecommended: '',
    },
    lounge: {
        title: '',
        labelMatch: '',
        labelCreateRoom: '',
        labelDualGame: '',
        labelQuadGame: '',
        labelCapacity: '',
        labelAvailable: '',
        labelWaiting: '',
    },
    match: {
        title: '',
        labelMatch: '',
        labelReceiveMatch: '',
        labelMatchLog: '',
        labelWins: '',
        labelLosses: '',
        fmtWin: '$win',
        fmtLoss: '$loss',
        msgNoMatch: '',
    },
    tournament: {
        title: '',
        labelCreateTournament: '',
        labelTournamentTitle: '',
        labelStart: '',
        labelEntry: '',
        labelCancelEntry: '',
        labelTitleUpcoming: '',
        labelTitleInPlay: '',
        labelTitleRecent: '',
        labelTournamentLog: '',
    },
    modal: {
        title: '',
        labelNickname: '',
        labelEntry: '',
        labelCancel: '',
        labelAccept: '',
        labelReject: '',
        labelCapacity: '',
        labelAvailable: '',
        titleSendMatchRequest: '',
        titleReceiveMatchRequest: '',
        titleWaitForOpponent: '',
        titleEntryTournament:  '',
    },
    friendRequest: {
        alreadyFriends: '$name ',
        usernameNotExists: '$name ',
        sendFriendReqSelf: '',
        invalidDeclineFriendReq: '',
        sentRequestSuccess: '$name ',
        acceptRequestSuccess: '$name ',
        declineRequestSuccess: '$name ',
        removeSuccess: '$name ',
        received: '$name ',
        accepted: '$name ',
        removed: '$name ',
    },
    matchRequest: {
        accepted: '',
        cancelled: '',
        rejected: '',
        userOffline: '',
    },
};
