'use strict';

export const labels_he = {
	langCode: 'he',
	langName: 'עברית',
    home: {
        title: 'Home',
        labelUsername: 'הזה עברית ', 
        labelPassword: 'הזה עברית ', 
        labelButtonLogin: 'הזה עברית ',
        labelButtonLogout: 'הזה עברית ',
        textSignUp: 'הזה עברית ',
        labelLinkSignUp: 'הזה עברית ',
    },
    register: {
        title: 'Register',
        labelUsername: 'הזה עברית ', 
        labelPassword: 'הזה עברית ', 
        labelPasswordConfirm: 'הזה עברית (הזה עברית )', 
        descUsername: ['[הזה עברית ] הזה עברית ,הזה עברית ,הזה עברית (_)', '[הזה עברית ] הזה עברית ,הזה עברית  הזה עברית ', '3הזה עברית 32הזה עברית '],
        descPassword: ['[הזה עברית ] הזה עברית (@_#$%&!.,+*~\')', '[הזה עברית ] הזה עברית ,הזה עברית ,הזה עברית ,הזה עברית  הזה עברית 1הזה עברית ', '8הזה עברית 24הזה עברית '],
        descPasswordConfirm: 'הזה עברית ',
        labelButtonConfirm: 'הזה עברית ',
        textConfirm: 'הזה עברית ',
        labelButtonRegister: 'הזה עברית ',
        labelButtonBack: 'הזה עברית ',
        textComplete: 'הזה עברית ',
        labelButtonLogin: 'הזה עברית ',
    },
    formErrorMessages: {
        valueMissing: 'הזה עברית ',
        patternMismatch: 'הזה עברית ',
        tooLong: 'הזה עברית ',
        tooShort: 'הזה עברית ',
        passwordIsNotSame: 'הזה עברית ',
        isExists: 'הזה עברית ',
        outOfRange: '',
        loginError1: '',
        loginError2: '',
    },

    dashboard: {
        title: 'Dashboard',
    },
    friends: {
        title: 'Friends',
        labelMatch: 'הזה עברית ',
        labelReceiveMatch: 'הזה עברית ',
        labelCancel: 'הזה עברית ',
        labelRmFriend: 'הזה עברית ',
        labelAccept: 'הזה עברית ',
        labelDecline: 'הזה עברית ',
        labelApply: 'הזה עברית ',
        labelSearch: 'הזה עברית ',
        labelSendRequest: 'הזה עברית ',
        msgNoUsername: 'הזה עברית ',
        msgNoFriends: 'הזה עברית ',
        labelListFriends: 'הזה עברית ',
        labelReceivedRequest: 'הזה עברית ',
        labelRecommended: 'הזה עברית ',
    },
    lounge: {
        title: 'Lounge',
        labelMatch: 'הזה עברית ',
        labelCreateRoom: 'הזה עברית ',
        labelDualGame: '2הזה עברית ',
        labelQuadGame: '4הזה עברית ',
        labelCapacity: 'הזה עברית ',
        labelAvailable: 'הזה עברית ',
        labelWaiting: 'הזה עברית ',
    },
    match: {
        title: '',
        labelMatch: 'הזה עברית ',
        labelReceiveMatch: 'הזה עברית ',
        labelMatchLog: 'הזה עברית ',
        labelWins: 'הזה עברית ',
        labelLosses: 'הזה עברית ',
        fmtWinLoss: '$win הזה עברית <br> $loss הזה עברית ',
    },
    tournament: {
        title: 'Tournament',
        labelCreateTournament: 'הזה עברית ',
        labelTournamentTitle: 'הזה עברית ',
        labelStart: 'הזה עברית ',
        labelEntry: 'הזה עברית ',
        labelCancelEntry: 'הזה עברית ',
        labelTitleUpcoming: 'הזה עברית ',
        labelTitleInPlay: 'הזה עברית ',
        labelTitleRecent: 'הזה עברית ',
        labelTournamentLog: 'הזה עברית ',
        descTournamentTitle: [''],
        descTournamentStart: [''],
        descNickname: [''],
    },
    modal: {
        title: '',
        labelNickname: 'הזה עברית ',
        labelEntry: 'הזה עברית ',
        labelCancel: 'הזה עברית ',
        labelAccept: 'הזה עברית ',
        labelReject: 'הזה עברית ',
        labelCapacity: 'הזה עברית ',
        labelAvailable: 'הזה עברית ',
        titleSendMatchRequest: 'הזה עברית ',
        titleReceiveMatchRequest: 'הזה עברית ',
        titleWaitForOpponent: 'הזה עברית ...',
        titleEntryTournament:  'הזה עברית ',
    },
    friendRequest: {
        alreadyFriends: '$name הזה עברית ',
        usernameNotExists: '$name הזה עברית ',
        sendFriendReqSelf: 'הזה עברית ',
        invalidDeclineFriendReq: 'הזה עברית ',
        sentRequestSuccess: '$name הזה עברית ',
        acceptRequestSuccess: '$name הזה עברית ',
        declineRequestSuccess: '$name הזה עברית ',
        removeSuccess: '$name הזה עברית ',
        received: '$name הזה עברית ',
        accepted: '$name הזה עברית ',
        removed: '$name הזה עברית ',
    },
    matchRequest: {
        accepted: 'הזה עברית ',
        cancelled: 'הזה עברית ',
        rejected: 'הזה עברית ',
        userOffline: 'הזה עברית ',
    },
};
