'use strict';

const labels_ja = {
    home: {
        title: 'Home',
        labelUsername: 'ユーザー名', 
        labelPassword: 'パスワード', 
        labelButtonLogin: 'ログイン',
        labelButtonLogout: 'ログアウト',
        textSignUp: '初めての方はこちら',
        labelLinkSignUp: '登録',
    },
    register: {
        title: 'Register',
        labelUsername: 'ユーザー名', 
        labelPassword: 'パスワード', 
        labelPasswordConfirm: 'パスワード(再入力)', 
        descUsername: ['[使用可能] 半角英小文字,半角数字,記号(_)', '[使用必須] 半角英小文字,半角数字 のいずれか', '3〜32文字'],
        descPassword: ['[使用可能] 半角英数字と記号(@_#$%&!.,+*~\')', '[使用必須] 英小文字,英大文字,数字,記号 のそれぞれ1文字', '8〜24文字'],
        descPasswordConfirm: '確認のためパスワードをもう一度入力してください',
        labelButtonConfirm: '確認する',
        textConfirm: '下記の内容で登録します',
        labelButtonRegister: '登録する',
        labelButtonBack: '修正する',
        textComplete: '登録完了しました',
        labelButtonLogin: 'ログイン',
    },
    formErrorMessages: {
        valueMissing: '入力してください',
        patternMismatch: '使用可能・使用必須の文字を確認してください',
        tooLong: '長すぎます',
        tooShort: '短すぎます',
        passwordIsNotSame: '同じパスワードを入力してください',
        isExists: 'このユーザー名は使われています',
    },

    dashboard: {
        title: 'Dashboard',
    },
    friends: {
        title: 'Friends',
        labelMatch: '対戦する',
        labelReceiveMatch: '対戦を受ける',
        labelCancel: 'キャンセル',
        labelRmFriend: '友達解除',
        labelAccept: '承諾',
        labelDecline: '削除',
        labelApply: '対戦する',
        labelSearch: '友達申請を送る',
        labelSendRequest: '送信',
        msgNoUsername: '友達申請を送るユーザー名を入力してください',
        labelListFriends: '友達一覧',
        labelReceivedRequest: '受け取った友達申請',
        labelRecommended: 'あなたへのおすすめ',
    },
    lounge: {
        title: 'Lounge',
        labelMatch: '対戦する',
        labelCreateRoom: '部屋を作成',
        labelDualGame: '2人対戦',
        labelQuadGame: '4人対戦',
        labelCapacity: '定員',
        labelAvailable: '募集中',
        labelWaiting: '対戦相手を募集中',
    },
    match: {
        title: '',
        labelMatch: '対戦する',
        labelReceiveMatch: '対戦を受ける',
        labelMatchLog: '対戦記録',
        labelWins: '勝',
        labelLosses: '敗',
    },
    tournament: {
        title: 'Tournament',
        labelCreateTournament: 'トーナメントを作成',
        labelTournamentTitle: 'トーナメント名',
        labelStart: '開始時刻',
        labelEntry: '出場する',
        labelCancelEntry: '取り消す',
        labelTitleUpcoming: '開催予定のトーナメント',
        labelTitleInPlay: '試合中のトーナメント',
        labelTitleRecent: '終了したトーナメント',
        labelTournamentLog: 'トーナメント記録',
    },
    modal: {
        title: '',
        labelNickname: 'ニックネーム',
        labelEntry: '出場申込',
        labelCancel: 'キャンセル',
        labelAccept: '対戦する',
        labelReject: 'やめておく',
        labelCapacity: '定員',
        labelAvailable: '募集中',
        titleSendMatchRequest: '対戦を申し込みました',
        titleReceiveMatchRequest: '対戦申し込みがありました',
        titleWaitForOpponent: '対戦相手を待っています...',
        titleEntryTournament:  'トーナメントに出場する',
    },
};
const labels_en = {
    home: {
        title: 'Home',
        labelUsername: 'username', 
        labelPassword: 'password', 
        labelButtonLogin: 'log in',
        labelButtonLogout: 'log out',
        textSignUp: 'If you don\'t have an account:',
        labelLinkSignUp: 'sign up',
    },
    register: {
        title: 'Register',
        labelUsername: 'username', 
        labelPassword: 'password', 
        labelPasswordConfirm: 'confirm password', 
        descUsername: ['[english] english,english,english(_)', '[english] english,english english', '3english32english'],
        descPassword: ['[english] english(@_#$%&!.,+*~\')', '[english] english,english,english,english english1english', '8english24english'],
        descPasswordConfirm: 'english',
        labelButtonConfirm: 'english',
        textConfirm: 'english',
        labelButtonRegister: 'english',
        labelButtonBack: 'english',
        textComplete: 'english',
        labelButtonLogin: 'english',
    },
    formErrorMessages: {
        valueMissing: 'This field is required.',
        patternMismatch: 'Please check the character type requirement.',
        tooLong: 'Too many characters.',
        tooShort: 'Too few characters.',
        passwordIsNotSame: 'The passwords do not match.',
        isExists: 'This username already exists.',
    },

    dashboard: {
        title: 'Dashboard',
    },
    friends: {
        title: 'Friends',
        labelMatch: 'english',
        labelReceiveMatch: 'english',
        labelCancel: 'english',
        labelRmFriend: 'english',
        labelAccept: 'english',
        labelDecline: 'english',
        labelApply: 'english',
        labelSearch: 'english',
        labelSendRequest: 'english',
        msgNoUsername: 'english',
        labelListFriends: 'english',
        labelReceivedRequest: 'english',
        labelRecommended: 'english',
    },
    lounge: {
        title: 'Lounge',
        labelMatch: 'english',
        labelCreateRoom: 'english',
        labelDualGame: '2english',
        labelQuadGame: '4english',
        labelCapacity: 'english',
        labelAvailable: 'english',
        labelWaiting: 'english',
    },
    match: {
        title: '',
        labelMatch: 'english',
        labelReceiveMatch: 'english',
        labelMatchLog: 'english',
        labelWins: 'english',
        labelLosses: 'english',
    },
    tournament: {
        title: 'Tournament',
        labelCreateTournament: 'english',
        labelTournamentTitle: 'english',
        labelStart: 'english',
        labelEntry: 'english',
        labelCancelEntry: 'english',
        labelTitleUpcoming: 'english',
        labelTitleInPlay: 'english',
        labelTitleRecent: 'english',
        labelTournamentLog: 'english',
    },
    modal: {
        title: '',
        labelNickname: 'english',
        labelEntry: 'english',
        labelCancel: 'english',
        labelAccept: 'english',
        labelReject: 'english',
        labelCapacity: 'english',
        labelAvailable: 'english',
        titleSendMatchRequest: 'english',
        titleReceiveMatchRequest: 'english',
        titleWaitForOpponent: 'english...',
        titleEntryTournament:  'english',
    },
};
const labels_la = {
    home: {
        title: '',
        labelUsername: '', 
        labelPassword: '', 
        labelButtonLogin: '',
        labelButtonLogout: '',
        textSignUp: '',
        labelLinkSignUp: '',
    },
    register: {
        title: '',
        labelUsername: '', 
        labelPassword: '', 
        labelPasswordConfirm: '', 
        descUsername: [''],
        descPassword: [''],
        descPasswordConfirm: '',
        labelButtonConfirm: '',
        textConfirm: '',
        labelButtonRegister: '',
        labelButtonBack: '',
        textComplete: '',
        labelButtonLogin: '',
    },
    formErrorMessages: {
        valueMissing: '',
        patternMismatch: '',
        tooLong: '',
        tooShort: '',
        passwordIsNotSame: '',
        isExists: '',
    },

    dashboard: {
        title: '',
    },
    friends: {
        title: '',
        labelMatch: '',
        labelReceiveMatch: '',
        labelCancel: '',
        labelRmFriend: '',
        labelAccept: '',
        labelDecline: '',
        labelApply: '',
        labelSearch: '',
        labelSendRequest: '',
        msgNoUsername: '',
        labelListFriends: '',
        labelReceivedRequest: '',
        labelRecommended: '',
    },
    lounge: {
        title: '',
        labelMatch: '',
        labelCreateRoom: '',
        labelDualGame: '',
        labelQuadGame: '',
        labelCapacity: '',
        labelAvailable: '',
        labelWaiting: '',
    },
    match: {
        title: '',
        labelMatch: '',
        labelReceiveMatch: '',
        labelMatchLog: '',
        labelWins: '',
        labelLosses: '',
    },
    tournament: {
        title: '',
        labelCreateTournament: '',
        labelTournamentTitle: '',
        labelStart: '',
        labelEntry: '',
        labelCancelEntry: '',
        labelTitleUpcoming: '',
        labelTitleInPlay: '',
        labelTitleRecent: '',
        labelTournamentLog: '',
    },
    modal: {
        title: '',
        labelNickname: '',
        labelEntry: '',
        labelCancel: '',
        labelAccept: '',
        labelReject: '',
        labelCapacity: '',
        labelAvailable: '',
        titleSendMatchRequest: '',
        titleReceiveMatchRequest: '',
        titleWaitForOpponent: '',
        titleEntryTournament:  '',
    },
};
const labels_fr = Object.getPrototypeOf(labels_la);
const labels_he = Object.getPrototypeOf(labels_la);
const languageLabels = {
    'en': labels_en,
    'ja': labels_ja,
    'fr': labels_fr,
    'la': labels_la,
    'he': labels_he,
};

const switchLabels = (language) => {
    Object.assign(labels, languageLabels[language]);
};

const getLanguage = () => {
    return localStorage.getItem('configLang') || 'en';
}

const labels = languageLabels[getLanguage()];

export { labels, switchLabels };
