'use strict';

import { CREATE_TOURNAMENT_TIMELIMIT_MIN, FRIENDS_MAX } from './env.js';

export const labels_fr = {
    langCode: 'fr',
    langName: 'français',
    common: {
        switchLang: 'Changer de langue',
        btnEnable: 'Le bouton sera activé lorsque des valeurs valides seront saisies.',
        logoutTokenExpired: 'Session expirée. Vous avez été déconnecté. Veuillez vous reconnecter.',
        disconnected: 'Déconnecté du serveur',
        disconnectedByNewLogin: 'Déconnecté en raison d’une nouvelle connexion sur le serveur',
        failUpdateDbLang: 'Échec de la sauvegarde des paramètres de langue',
    },
    home: {
        title: 'Accueil',
        labelUsername: 'Nom d’utilisateur',
        labelPassword: 'Mot de passe',
        labelButtonLogin: 'Se connecter',
        labelButtonLogout: 'Se déconnecter',
        textSignUp: 'Vous n’avez pas encore de compte ?',
        labelLinkSignUp: 'Créer un compte',
        fail42Login1: 'Aucun compte disponible avec 42Login. Veuillez vous inscrire via l\'inscription.',
        fail42Login2: 'Échec de la connexion avec 42Login.',
    },
    register: {
        title: 'Register',
        labelUsername: 'Nom d’utilisateur',
        labelPassword: 'Mot de passe',
        labelPasswordConfirm: 'Confirmez le mot de passe',
        descUsername: ['[Disponible] lettres minuscules, chiffres et symboles (_)]', '[Obligatoire] une lettre minuscule ou un chiffre', '3-32 caractères'],
        descPassword: ['[Disponible] Caractères alphanumériques et symboles (@_#$%&!.,+*~\')', '[Obligatoire] une majuscule, une minuscule, un chiffre et un symbol', '8-24 caractères'],
        descPasswordConfirm: 'Veuillez saisir à nouveau votre mot de passe pour confirmation',
        labelButtonConfirm: 'Confirmer',
        textConfirm: 'Souhaitez-vous vous enregistrer avec les informations suivantes ?',
        labelButtonRegister: 'S’inscrire',
        labelButtonBack: 'Modifier',
        textComplete: 'Enregistrement terminé',
        labelButtonLogin: 'Se connecter',
    },
    formErrorMessages: {
        valueMissing: 'Veuillez saisir une valeur',
        patternMismatch: 'Veuillez vérifier les caractères disponibles et requis',
        tooLong: 'Trop long',
        tooShort: 'Trop court',
        passwordIsNotSame: 'Veuillez saisir le même mot de passe',
        isExists: 'Ce nom d’utilisateur est utilisé',
        outOfRange: 'Cette date et heure ne peuvent pas être spécifiées',
        startTimeInvalid: `Veuillez définir l'heure de début du tournoi pour qu'elle soit au moins ${CREATE_TOURNAMENT_TIMELIMIT_MIN} minutes à partir de maintenant.`,
        intervalError: 'Un intervalle d’au moins 6 heures est requis entre les tournois.',
        tournamentNameAlreadyExists: 'Le nom du tournoi existe déjà.',
        loginError1: 'Veuillez vérifier le nom d’utilisateur et le mot de passe',
        loginError2: 'quelque chose s’est mal passé',
    },
    dashboard: {
        title: 'Tableau de bord',
        labelChangeAvatar: 'Changer l’avatar',
        labelCancel: 'Annuler',
        labelUpload: 'Changer',
        msgAvatarSwitched : 'L’avatar a été modifié',
        msgFailAvatarUpload: '',
        msgInvalidFile : 'Fichier non valide',
        msgInvalidFileFormat : 'Format de fichier non valide (.jpg, .png uniquement)',
        labelViewAllFriends: 'Voir la liste complète des amis',
    },
    friends: {
        title: 'Amis',
        labelMatch: 'jouer contre',
        labelMatchAria: 'Jouer contre $friend ',
        labelReceiveMatch: 'Recevoir la rencontre',
        labelCancel: 'Annuler',
        labelRmFriend: 'Annuler l’amitié',
        labelRmFriendAria: 'Annuler l’amitié avec $friend ',
        labelAccept: 'Accepter',
        labelDecline: 'Supprimer',
        labelApply: 'Jouer contre',
        labelSearch: 'Envoyer une demande d’ami',
        labelSendRequest: 'Envoyer',
        labelRequest: 'être amis',
        labelRequestAria: 'Envoyer une demande d\'amitié à $player',
        msgNoUsername: 'Veuillez entrer un nom d’utilisateur à qui envoyer une demande d’ami',
        msgNoFriends: 'Vous n’avez pas encore d’amis',
        labelListFriends: 'Liste d’amis',
        labelReceivedRequest: 'Demandes d’amis reçues',
        labelRecommended: 'Recommandations pour vous',
        msgNoRecommended: 'aucune recommandation',
        msgFriendsFull: `Vous avez atteint la limite maximale de ${FRIENDS_MAX} amis.<br>Si vous souhaitez ajouter un autre joueur en tant qu'ami, veuillez supprimer un ami existant pour libérer de l'espace.`,
        labelOnline: 'En ligne',
        labelOffline: 'Hors ligne',
        msgChangeFriendOnline: '$friend est maintenant $online ',
    },
    lounge: {
        title: 'Lounge',
        labelMatch: 'Rejoindre',
        labelMatchDual: 'Rejoindre un match à 2 joueurs',
        labelMatchQuad: 'Rejoindre un match à 4 joueurs',
        labelCreateRoom: 'Créer une salle',
        labelDualGame: 'Jeu à 2 joueurs',
        labelQuadGame: 'Jeu à 4 joueur',
        labelCapacity: 'Capacité',
        labelAvailable: 'Disponible',
        labelWaiting: 'Recherche d’adversaires',
    },
    match: {
        title: 'Match',
        labelMatch: 'jouer contre',
        labelReceiveMatch: 'Recevoir le match',
        labelMatchLog: 'Journal du match',
        fmtWin: '$win victoires',
        fmtMatches: '$num matchs',
        msgNoMatch: 'aucune match',
        msgReconnectMatch: 'Reconnexion au jeu en cours',
    },
    tournament: {
        title: 'Tournament',
        labelCreateTournament: 'Créer un tournoi',
        msgCreateDone: '$tournament - $start a été créé',
        labelTournamentTitle: 'Nom du tournoi',
        labelStart: 'Heure de début',
        labelEntry: 'Entrer',
        labelCancelEntry: 'Annuler',
        labelTitleUpcoming: 'Tournoi à venir',
        labelTitleOnGoing: 'Tournoi en cours',
        labelTitleRecent: 'Tournoi terminé',
        labelTournamentLog: 'Journal du tournoi',
        labelCanceledRound: '(Annulation en raison de la défaite du joueur)',
        labelUpdateLists: 'Mettre à jour les listes',
        descTournamentTitle: ['Vous pouvez utiliser des lettres minuscules, des chiffres, des hiragana, des katakana, des kanji et des symboles(@_#$%&!.+*~)', 'Entre 3 et 50 caractères'],
        descTournamentStart: [`[Plage autorisée] À partir de ${CREATE_TOURNAMENT_TIMELIMIT_MIN} minutes plus tard jusqu’à 1 mois plus tard.`, '[entre les tournois] Au moins 6 heures'],
        descNickname: ['Vous pouvez utiliser des lettres minuscules, des chiffres, des hiragana, des katakana, des kanji et des symboles(@_#$%&!.+*~)', 'Entre 3 et 20 caractères'],
        labelNextMatch: 'Prochain Match',
        labelRound1: 'Premier Tour',
        labelRound2: 'Deuxième Tour',
        labelRound3: 'Troisième Tour',
        labelRoundThirdPlaceRound: 'Match pour la Troisième Place',
        labelRoundSemiFinal: 'Demi-finale',
        labelRoundFinal: 'Finale',
        labelByePlayer: 'Bye',
        labelWinner: 'Le numéro <strong>1</strong>',
        labelSecondPlace: 'Le numéro <strong>2</strong>',
        labelThirdPlace: 'Le numéro <strong>3</strong>',
        msgNoUpcoming: 'Pas de tournoi à venir',
        msgNoOngoing: 'Pas de tournoi en cours',
        msgNoFinished: 'Pas de tournoi terminé',
        msgNoEntered: 'Aucun tournoi inscrit',
        labelWaitBye: 'Victoire Bye',
        msgWaitBye: '<p>Veuillez attendre la fin du match</p>',
        labelWaitLose: 'Impossible d’avancer',
        msgWaitLose: '<p>Veuillez attendre la fin du tournoi</p>',
        labelWaitStart: 'En attente de début',
        msgWaitStart: '<p>Le tournoi commencera bientôt</p>',
        labelWaitRound: 'En attente de la fin du tour',
        msgWaitRound: '<p>Veuillez attendre la fin du tour</p>',
        labelWaitSemiFinal: 'En attente du match de demi-finale',
        msgWaitSemiFinal: '<p>Veuillez attendre le début du match de demi-finale</p>',
        labelWaitFinal: 'En attente du match de finale',
        msgWaitFinal: '<p>Veuillez attendre le début du match de finale</p>',
        labelFinalOnGoing: 'Finale en cours',
        msgFinalOnGoing: '<p>Veuillez attendre la fin du match de finale</p>',
        msgEntryDone: 'L’inscription au tournoi $tournament est complétée',
        msgNoEntry: 'Aucune inscription pour le tournoi',
        msgInvalidEntry: 'Demande invalide, comme le dépassement du délai d’inscription',
        msgPrepare: 'Il reste 5 minutes avant le début du tournoi $tournament',
        msgEnterRoom: 'Déplacement vers la salle d’attente pour le tournoi $tournament',
        msgCanceled: 'Le tournoi $tournament a été annulé en raison d’un nombre insuffisant de participants',
        msgStart: 'Début du tournoi $tournament',
        msgFinished: 'Le tournoi $tournament est terminé',
        msgDeadHasPassed: 'Le délai d’inscription pour le tournoi $tournament est dépassé',
        msgEntryCanceled: 'L’inscription au tournoi $tournament a été annulée',
        msgEntryDupNickname: 'Un surnom avec le même nom est déjà utilisé',
        msgAlreadyEntered: 'Vous êtes déjà inscrit à ce tournoi',
        msgCapacityFull: 'Impossible de s’inscrire au tournoi en raison de la capacité maximale',
        msgEntryInvalidTournament: 'Demande pour un tournoi invalide',
        msgEntryInvalidPlayer: 'Impossible de s’inscrire au tournoi',
    },
    modal: {
        labelNickname: 'pseudo',
        labelEntry: 'Demande d’entrée',
        labelCancel: 'Annuler',
        labelAccept: 'jouer contre',
        labelReject: 'Ne le fais pas',
        labelCapacity: 'Capacité',
        labelAvailable: 'Disponible',
        labelExitGame:  'quitter',
        labelReturnToGame:  'Retourner au jeu',
        titleSendMatchRequest: 'Vous avez demandé un match',
        titleReceiveMatchRequest: 'Vous avez reçu une demande de match',
        titleWaitForOpponent: 'En attente d’un adversaire...',
        titleEntryTournament:  'Entrer',
        titleExitGame:  'Quitter le jeu ?',
    },
    friendRequest: {
        alreadyFriends: '$name est déjà un ami',
        usernameNotExists: '$name n’existe pas',
        sendFriendReqSelf: 'Vous ne pouvez pas être ami avec vous-même',
        invalidDeclineFriendReq: 'Impossible de supprimer la demande d’ami',
        sentRequestSuccess: 'Demande d’amitié envoyée à $name ',
        acceptRequestSuccess: 'Vous êtes maintenant ami avec $name ',
        declineRequestSuccess: 'La demande d’amitié de $name a été annulé',
        removeSuccess: 'Vous avez supprimé l’amitié de $name',
        mutualReq: '$name vous a déjà envoyé une demande d’amitié',
        alreadyReq: 'Vous avez déjà envoyé une demande d’amitié à $name',
        received: 'Vous avez reçu une demande d’amitié de la part de $name ',
        accepted: '$name a accepté votre demande d’amitié',
        removed: 'Vous n’êtes plus ami avec $name',
        missedRequestAccept: '$name a essayé d’accepter votre demande d’amitié, mais votre liste d’amis a atteint sa limite. Veuillez supprimer certains amis pour libérer de l’espace.',
        acceptRequestFailedFull: 'Vous n’avez pas pu devenir amis avec $name car votre liste d’amis est pleine pour le moment.',
        acceptRequestFailedFull2: 'Vous n’avez pas pu devenir amis car la limite d’amis a été atteinte. Veuillez supprimer certains amis pour libérer de l’espace.',
    },
    matchRequest: {
        accepted: 'Le match va commencer',
        cancelled: 'Votre adversaire a annulé votre match',
        rejected: 'L’adversaire n’est pas d’humeur à jouer',
        userOffline: 'Votre adversaire est hors ligne',
        playerNotWaitingStatus: 'Votre adversaire est occupé',
        msgCannotRequestInTournament: 'Les demandes de match ne peuvent pas être effectuées pendant un tournoi',
        msgCannotRequestInMatch: 'Impossible de demander un autre match pendant un match',
        msgCannotRequestInMatchWaiting: 'Les demandes de match ne peuvent pas être effectuées en attendant un match',
    },
};
