'use strict';

export const labels_ar = {
	langCode: 'ar',
	langName: 'العربية',
    home: {
        title: 'Home',
        labelUsername: ' يؤُلاءِ العربية',
        labelPassword: ' يؤُلاءِ العربية',
        labelButtonLogin: ' يؤُلاءِ العربية',
        labelButtonLogout: ' يؤُلاءِ العربية',
        textSignUp: ' يؤُلاءِ العربية',
        labelLinkSignUp: ' يؤُلاءِ العربية',
    },
    register: {
        title: 'Register',
        labelUsername: ' يؤُلاءِ العربية',
        labelPassword: ' يؤُلاءِ العربية',
        labelPasswordConfirm: ' يؤُلاءِ العربية( يؤُلاءِ العربية)',
        descUsername: ['[ يؤُلاءِ العربية] يؤُلاءِ العربية, يؤُلاءِ العربية, يؤُلاءِ العربية(_)', '[ يؤُلاءِ العربية] يؤُلاءِ العربية, يؤُلاءِ العربية يؤُلاءِ العربية', '3 يؤُلاءِ العربية32 يؤُلاءِ العربية'],
        descPassword: ['[ يؤُلاءِ العربية] يؤُلاءِ العربية(@_#$%&!.,+*~\')', '[ يؤُلاءِ العربية] يؤُلاءِ العربية, يؤُلاءِ العربية, يؤُلاءِ العربية, يؤُلاءِ العربية يؤُلاءِ العربية1 يؤُلاءِ العربية', '8 يؤُلاءِ العربية24 يؤُلاءِ العربية'],
        descPasswordConfirm: ' يؤُلاءِ العربية',
        labelButtonConfirm: ' يؤُلاءِ العربية',
        textConfirm: ' يؤُلاءِ العربية',
        labelButtonRegister: ' يؤُلاءِ العربية',
        labelButtonBack: ' يؤُلاءِ العربية',
        textComplete: ' يؤُلاءِ العربية',
        labelButtonLogin: ' يؤُلاءِ العربية',
    },
    formErrorMessages: {
        valueMissing: ' يؤُلاءِ العربية',
        patternMismatch: ' يؤُلاءِ العربية',
        tooLong: ' يؤُلاءِ العربية',
        tooShort: ' يؤُلاءِ العربية',
        passwordIsNotSame: ' يؤُلاءِ العربية',
        isExists: ' يؤُلاءِ العربية',
    },

    dashboard: {
        title: 'Dashboard',
    },
    friends: {
        title: 'Friends',
        labelMatch: ' يؤُلاءِ العربية',
        labelReceiveMatch: ' يؤُلاءِ العربية',
        labelCancel: ' يؤُلاءِ العربية',
        labelRmFriend: ' يؤُلاءِ العربية',
        labelAccept: ' يؤُلاءِ العربية',
        labelDecline: ' يؤُلاءِ العربية',
        labelApply: ' يؤُلاءِ العربية',
        labelSearch: ' يؤُلاءِ العربية',
        labelSendRequest: ' يؤُلاءِ العربية',
        msgNoUsername: ' يؤُلاءِ العربية',
        msgNoFriends: ' يؤُلاءِ العربية',
        labelListFriends: ' يؤُلاءِ العربية',
        labelReceivedRequest: ' يؤُلاءِ العربية',
        labelRecommended: ' يؤُلاءِ العربية',
    },
    lounge: {
        title: 'Lounge',
        labelMatch: ' يؤُلاءِ العربية',
        labelCreateRoom: ' يؤُلاءِ العربية',
        labelDualGame: '2 يؤُلاءِ العربية',
        labelQuadGame: '4 يؤُلاءِ العربية',
        labelCapacity: ' يؤُلاءِ العربية',
        labelAvailable: ' يؤُلاءِ العربية',
        labelWaiting: ' يؤُلاءِ العربية',
    },
    match: {
        title: '',
        labelMatch: ' يؤُلاءِ العربية',
        labelReceiveMatch: ' يؤُلاءِ العربية',
        labelMatchLog: ' يؤُلاءِ العربية',
        labelWins: ' يؤُلاءِ العربية',
        labelLosses: ' يؤُلاءِ العربية',
        fmtWinLoss: '$win يؤُلاءِ العربية  $loss يؤُلاءِ العربية',
    },
    tournament: {
        title: 'Tournament',
        labelCreateTournament: ' يؤُلاءِ العربية',
        labelTournamentTitle: ' يؤُلاءِ العربية',
        labelStart: ' يؤُلاءِ العربية',
        labelEntry: ' يؤُلاءِ العربية',
        labelCancelEntry: ' يؤُلاءِ العربية',
        labelTitleUpcoming: ' يؤُلاءِ العربية',
        labelTitleInPlay: ' يؤُلاءِ العربية',
        labelTitleRecent: ' يؤُلاءِ العربية',
        labelTournamentLog: ' يؤُلاءِ العربية',
    },
    modal: {
        title: '',
        labelNickname: ' يؤُلاءِ العربية',
        labelEntry: ' يؤُلاءِ العربية',
        labelCancel: ' يؤُلاءِ العربية',
        labelAccept: ' يؤُلاءِ العربية',
        labelReject: ' يؤُلاءِ العربية',
        labelCapacity: ' يؤُلاءِ العربية',
        labelAvailable: ' يؤُلاءِ العربية',
        titleSendMatchRequest: ' يؤُلاءِ العربية',
        titleReceiveMatchRequest: ' يؤُلاءِ العربية',
        titleWaitForOpponent: ' يؤُلاءِ العربية...',
        titleEntryTournament:  ' يؤُلاءِ العربية',
    },
    friendRequest: {
        alreadyFriends: '$name يؤُلاءِ العربية',
        usernameNotExists: '$name يؤُلاءِ العربية',
        sendFriendReqSelf: ' يؤُلاءِ العربية',
        invalidDeclineFriendReq: ' يؤُلاءِ العربية',
        sentRequestSuccess: '$name يؤُلاءِ العربية',
        acceptRequestSuccess: '$name يؤُلاءِ العربية',
        declineRequestSuccess: '$name يؤُلاءِ العربية',
        removeSuccess: '$name يؤُلاءِ العربية',
        received: '$name يؤُلاءِ العربية',
        accepted: '$name يؤُلاءِ العربية',
        removed: '$name يؤُلاءِ العربية',
    },
    matchRequest: {
        accepted: 'يؤُلاءِ العربية',
        cancelled: 'يؤُلاءِ العربية',
        rejected: 'يؤُلاءِ العربية',
        userOffline: 'يؤُلاءِ العربية',
    },
};
