'use strict';

const labels_ja = {
    home: {
        title: 'Home',
        labelUsername: 'ユーザー名', 
        labelPassword: 'パスワード', 
        labelButtonLogin: 'ログイン',
        labelButtonLogout: 'ログアウト',
        textSignUp: '初めての方はこちら',
        labelLinkSignUp: '登録',
    },
    register: {
        title: 'Register',
        labelUsername: 'ユーザー名', 
        labelPassword: 'パスワード', 
        labelPasswordConfirm: 'パスワード(再入力)', 
        descUsername: ['[使用可能] 半角英小文字,半角数字,記号(_)', '[使用必須] 半角英小文字,半角数字 のいずれか', '3〜32文字'],
        descPassword: ['[使用可能] 半角英数字と記号(@_#$%&!.,+*~\')', '[使用必須] 英小文字,英大文字,数字,記号 のそれぞれ1文字', '8〜24文字'],
        descPasswordConfirm: '確認のためパスワードをもう一度入力してください',
        labelButtonConfirm: '確認する',
        textConfirm: '下記の内容で登録します',
        labelButtonRegister: '登録する',
        labelButtonBack: '修正する',
        textComplete: '登録完了しました',
        labelButtonLogin: 'ログイン',
    },
    formErrorMessages: {
        valueMissing: '入力してください',
        patternMismatch: '使用可能・使用必須の文字を確認してください',
        tooLong: '長すぎます',
        tooShort: '短すぎます',
        passwordIsNotSame: '同じパスワードを入力してください',
        isExists: 'このユーザー名は使われています',
    },

    dashboard: {
        title: 'Dashboard',
    },
    friends: {
        title: 'Friends',
        labelMatch: '対戦する',
        labelReceiveMatch: '対戦を受ける',
        labelCancel: 'キャンセル',
        labelRmFriend: '友達解除',
        labelAccept: '承諾',
        labelDecline: '削除',
        labelApply: '対戦する',
        labelSearch: '友達申請を送る',
        labelSendRequest: '送信',
        msgNoUsername: '友達申請を送るユーザー名を入力してください',
        msgNoFriends: '友達はまだいません',
        labelListFriends: '友達一覧',
        labelReceivedRequest: '受け取った友達申請',
        labelRecommended: 'あなたへのおすすめ',
    },
    lounge: {
        title: 'Lounge',
        labelMatch: '対戦する',
        labelCreateRoom: '部屋を作成',
        labelDualGame: '2人対戦',
        labelQuadGame: '4人対戦',
        labelCapacity: '定員',
        labelAvailable: '募集中',
        labelWaiting: '対戦相手を募集中',
    },
    match: {
        title: '',
        labelMatch: '対戦する',
        labelReceiveMatch: '対戦を受ける',
        labelMatchLog: '対戦記録',
        labelWins: '勝',
        labelLosses: '敗',
        fmtWinLoss: '$win勝 $loss敗',
    },
    tournament: {
        title: 'Tournament',
        labelCreateTournament: 'トーナメントを作成',
        labelTournamentTitle: 'トーナメント名',
        labelStart: '開始時刻',
        labelEntry: '出場する',
        labelCancelEntry: '取り消す',
        labelTitleUpcoming: '開催予定のトーナメント',
        labelTitleInPlay: '試合中のトーナメント',
        labelTitleRecent: '終了したトーナメント',
        labelTournamentLog: 'トーナメント記録',
    },
    modal: {
        title: '',
        labelNickname: 'ニックネーム',
        labelEntry: '出場申込',
        labelCancel: 'キャンセル',
        labelAccept: '対戦する',
        labelReject: 'やめておく',
        labelCapacity: '定員',
        labelAvailable: '募集中',
        titleSendMatchRequest: '対戦を申し込みました',
        titleReceiveMatchRequest: '対戦申し込みがありました',
        titleWaitForOpponent: '対戦相手を待っています...',
        titleEntryTournament:  'トーナメントに出場する',
    },
    friendRequest: {
        alreadyFriends: '$name さんはすでに友達です',
        usernameNotExists: '$name は存在しません',
        sendFriendReqSelf: '自分自身は友達になれないのですよ',
        invalidDeclineFriendReq: '友達申請の削除ができませんでした',
        sentRequestSuccess: '$name さんに友達申請が送信されました',
        acceptRequestSuccess: '$name さんと友達になりました',
        declineRequestSuccess: '$name さんの友達申請を削除しました',
        removeSuccess: '$name さんとの友達を解除しました',
        received: '$name さんから友達申請が来ました',
        accepted: '$name さんが友達申請を承認しました',
        removed: '$name さんと友達じゃなくなりました',
    },
};
const labels_en = {
    home: {
        title: 'Home',
        labelUsername: 'username', 
        labelPassword: 'password', 
        labelButtonLogin: 'log in',
        labelButtonLogout: 'log out',
        textSignUp: 'If you don\'t have an account:',
        labelLinkSignUp: 'sign up',
    },
    register: {
        title: 'Register',
        labelUsername: 'username', 
        labelPassword: 'password', 
        labelPasswordConfirm: 'confirm password', 
        descUsername: ['You can use lowercase alphabets, numbers, and underscore (a-z 0-9 _)', 'You need to use at least one alphabet or number', 'Between 3 and 32 characters long'],
        descPassword: ['You can use uppercase and lowercase alphabets, numbers, and following symbols (@_#$%&!.,+*~\')', 'You need to use at least one uppercase, one lowercase, one number, and one symbol', 'Between 8 and 24 characters long'],
        descPasswordConfirm: 'Please confirm the password',
        labelButtonConfirm: 'confirm',
        textConfirm: 'Do you want to register with the following information?',
        labelButtonRegister: 'register',
        labelButtonBack: 'go back',
        textComplete: 'Registration complete.',
        labelButtonLogin: 'log in',
    },
    formErrorMessages: {
        valueMissing: 'This field is required.',
        patternMismatch: 'Please check the character type requirement.',
        tooLong: 'Too many characters.',
        tooShort: 'Too few characters.',
        passwordIsNotSame: 'The passwords do not match.',
        isExists: 'This username is already talen.',
    },

    dashboard: {
        title: 'Dashboard',
    },
    friends: {
        title: 'Friends',
        labelMatch: 'start a match',
        labelReceiveMatch: 'take the match',
        labelCancel: 'cancel',
        labelRmFriend: 'remove friend',
        labelAccept: 'accept',
        labelDecline: 'decline',
        labelApply: 'start a match',
        labelSearch: 'send friend request',
        labelSendRequest: 'send',
        msgNoUsername: 'Enter a username to send friend request',
        msgNoFriends: 'no friends yet',
        labelListFriends: 'friends',
        labelReceivedRequest: 'friend requests',
        labelRecommended: 'recommended',
    },
    lounge: {
        title: 'Lounge',
        labelMatch: 'start a match',
        labelCreateRoom: 'create a room',
        labelDualGame: '2-player match',
        labelQuadGame: '4-player match',
        labelCapacity: 'capacity',
        labelAvailable: 'available',
        labelWaiting: 'looking for an opponent',
    },
    match: {
        title: '',
        labelMatch: 'start a match',
        labelReceiveMatch: 'take the match',
        labelMatchLog: 'match log',
        labelWins: 'wins',
        labelLosses: 'losses',
        fmtWinLoss: '$win wins, $loss losses',
    },
    tournament: {
        title: 'Tournament',
        labelCreateTournament: 'create a tournament',
        labelTournamentTitle: 'tournament title',
        labelStart: 'start time',
        labelEntry: 'entry',
        labelCancelEntry: 'cancel',
        labelTitleUpcoming: 'upcoming tournaments',
        labelTitleInPlay: 'ongoing tournaments',
        labelTitleRecent: 'finished tournaments',
        labelTournamentLog: 'tournament log',
    },
    modal: {
        title: '',
        labelNickname: 'nickname',
        labelEntry: 'entry',
        labelCancel: 'cancel',
        labelAccept: 'accept',
        labelReject: 'reject',
        labelCapacity: 'capacity',
        labelAvailable: 'available',
        titleSendMatchRequest: 'sent a match request',
        titleReceiveMatchRequest: 'you received a match request',
        titleWaitForOpponent: 'waiting for an opponent...',
        titleEntryTournament:  'participate in tournament',
    },
    friendRequest: {
        alreadyFriends: '$name is already your friend',
        usernameNotExists: '$name does not exist',
        sendFriendReqSelf: 'you cannot be a friend of yourself',
        invalidDeclineFriendReq: 'failed to delete friend request',
        sentRequestSuccess: 'friend request has been sent to $name',
        acceptRequestSuccess: '$name is now your friend',
        declineRequestSuccess: 'friend request from $name has been deleted',
        removeSuccess: '$name is no longer your friend',
        received: '$name has sent you a friend request',
        accepted: '$name has accepted your friend request',
        removed: '$name is no longer your friend',
    },
};
const labels_la = {
    home: {
        title: '',
        labelUsername: '', 
        labelPassword: '', 
        labelButtonLogin: '',
        labelButtonLogout: '',
        textSignUp: '',
        labelLinkSignUp: '',
    },
    register: {
        title: '',
        labelUsername: '', 
        labelPassword: '', 
        labelPasswordConfirm: '', 
        descUsername: [''],
        descPassword: [''],
        descPasswordConfirm: '',
        labelButtonConfirm: '',
        textConfirm: '',
        labelButtonRegister: '',
        labelButtonBack: '',
        textComplete: '',
        labelButtonLogin: '',
    },
    formErrorMessages: {
        valueMissing: '',
        patternMismatch: '',
        tooLong: '',
        tooShort: '',
        passwordIsNotSame: '',
        isExists: '',
    },

    dashboard: {
        title: '',
    },
    friends: {
        title: '',
        labelMatch: '',
        labelReceiveMatch: '',
        labelCancel: '',
        labelRmFriend: '',
        labelAccept: '',
        labelDecline: '',
        labelApply: '',
        labelSearch: '',
        labelSendRequest: '',
        msgNoUsername: '',
        msgNoFriends: '',
        labelListFriends: '',
        labelReceivedRequest: '',
        labelRecommended: '',
    },
    lounge: {
        title: '',
        labelMatch: '',
        labelCreateRoom: '',
        labelDualGame: '',
        labelQuadGame: '',
        labelCapacity: '',
        labelAvailable: '',
        labelWaiting: '',
    },
    match: {
        title: '',
        labelMatch: '',
        labelReceiveMatch: '',
        labelMatchLog: '',
        labelWins: '',
        labelLosses: '',
        fmtWinLoss: '$win $loss',
    },
    tournament: {
        title: '',
        labelCreateTournament: '',
        labelTournamentTitle: '',
        labelStart: '',
        labelEntry: '',
        labelCancelEntry: '',
        labelTitleUpcoming: '',
        labelTitleInPlay: '',
        labelTitleRecent: '',
        labelTournamentLog: '',
    },
    modal: {
        title: '',
        labelNickname: '',
        labelEntry: '',
        labelCancel: '',
        labelAccept: '',
        labelReject: '',
        labelCapacity: '',
        labelAvailable: '',
        titleSendMatchRequest: '',
        titleReceiveMatchRequest: '',
        titleWaitForOpponent: '',
        titleEntryTournament:  '',
    },
    friendRequest: {
        alreadyFriends: '$name ',
        usernameNotExists: '$name ',
        sendFriendReqSelf: '',
        invalidDeclineFriendReq: '',
        sentRequestSuccess: '$name ',
        acceptRequestSuccess: '$name ',
        declineRequestSuccess: '$name ',
        removeSuccess: '$name ',
        received: '$name ',
        accepted: '$name ',
        removed: '$name ',
    },
};
const labels_fr = labels_la;
const labels_he = {
    home: {
        title: 'Home',
        labelUsername: 'הזה עברית ', 
        labelPassword: 'הזה עברית ', 
        labelButtonLogin: 'הזה עברית ',
        labelButtonLogout: 'הזה עברית ',
        textSignUp: 'הזה עברית ',
        labelLinkSignUp: 'הזה עברית ',
    },
    register: {
        title: 'Register',
        labelUsername: 'הזה עברית ', 
        labelPassword: 'הזה עברית ', 
        labelPasswordConfirm: 'הזה עברית (הזה עברית )', 
        descUsername: ['[הזה עברית ] הזה עברית ,הזה עברית ,הזה עברית (_)', '[הזה עברית ] הזה עברית ,הזה עברית  הזה עברית ', '3הזה עברית 32הזה עברית '],
        descPassword: ['[הזה עברית ] הזה עברית (@_#$%&!.,+*~\')', '[הזה עברית ] הזה עברית ,הזה עברית ,הזה עברית ,הזה עברית  הזה עברית 1הזה עברית ', '8הזה עברית 24הזה עברית '],
        descPasswordConfirm: 'הזה עברית ',
        labelButtonConfirm: 'הזה עברית ',
        textConfirm: 'הזה עברית ',
        labelButtonRegister: 'הזה עברית ',
        labelButtonBack: 'הזה עברית ',
        textComplete: 'הזה עברית ',
        labelButtonLogin: 'הזה עברית ',
    },
    formErrorMessages: {
        valueMissing: 'הזה עברית ',
        patternMismatch: 'הזה עברית ',
        tooLong: 'הזה עברית ',
        tooShort: 'הזה עברית ',
        passwordIsNotSame: 'הזה עברית ',
        isExists: 'הזה עברית ',
    },

    dashboard: {
        title: 'Dashboard',
    },
    friends: {
        title: 'Friends',
        labelMatch: 'הזה עברית ',
        labelReceiveMatch: 'הזה עברית ',
        labelCancel: 'הזה עברית ',
        labelRmFriend: 'הזה עברית ',
        labelAccept: 'הזה עברית ',
        labelDecline: 'הזה עברית ',
        labelApply: 'הזה עברית ',
        labelSearch: 'הזה עברית ',
        labelSendRequest: 'הזה עברית ',
        msgNoUsername: 'הזה עברית ',
        msgNoFriends: 'הזה עברית ',
        labelListFriends: 'הזה עברית ',
        labelReceivedRequest: 'הזה עברית ',
        labelRecommended: 'הזה עברית ',
    },
    lounge: {
        title: 'Lounge',
        labelMatch: 'הזה עברית ',
        labelCreateRoom: 'הזה עברית ',
        labelDualGame: '2הזה עברית ',
        labelQuadGame: '4הזה עברית ',
        labelCapacity: 'הזה עברית ',
        labelAvailable: 'הזה עברית ',
        labelWaiting: 'הזה עברית ',
    },
    match: {
        title: '',
        labelMatch: 'הזה עברית ',
        labelReceiveMatch: 'הזה עברית ',
        labelMatchLog: 'הזה עברית ',
        labelWins: 'הזה עברית ',
        labelLosses: 'הזה עברית ',
        fmtWinLoss: '$win הזה עברית <br> $loss הזה עברית ',
    },
    tournament: {
        title: 'Tournament',
        labelCreateTournament: 'הזה עברית ',
        labelTournamentTitle: 'הזה עברית ',
        labelStart: 'הזה עברית ',
        labelEntry: 'הזה עברית ',
        labelCancelEntry: 'הזה עברית ',
        labelTitleUpcoming: 'הזה עברית ',
        labelTitleInPlay: 'הזה עברית ',
        labelTitleRecent: 'הזה עברית ',
        labelTournamentLog: 'הזה עברית ',
    },
    modal: {
        title: '',
        labelNickname: 'הזה עברית ',
        labelEntry: 'הזה עברית ',
        labelCancel: 'הזה עברית ',
        labelAccept: 'הזה עברית ',
        labelReject: 'הזה עברית ',
        labelCapacity: 'הזה עברית ',
        labelAvailable: 'הזה עברית ',
        titleSendMatchRequest: 'הזה עברית ',
        titleReceiveMatchRequest: 'הזה עברית ',
        titleWaitForOpponent: 'הזה עברית ...',
        titleEntryTournament:  'הזה עברית ',
    },
    friendRequest: {
        alreadyFriends: '$name הזה עברית ',
        usernameNotExists: '$name הזה עברית ',
        sendFriendReqSelf: 'הזה עברית ',
        invalidDeclineFriendReq: 'הזה עברית ',
        sentRequestSuccess: '$name הזה עברית ',
        acceptRequestSuccess: '$name הזה עברית ',
        declineRequestSuccess: '$name הזה עברית ',
        removeSuccess: '$name הזה עברית ',
        received: '$name הזה עברית ',
        accepted: '$name הזה עברית ',
        removed: '$name הזה עברית ',
    },
};
const labels_ar = {
    home: {
        title: 'Home',
        labelUsername: ' يؤُلاءِ العربية', 
        labelPassword: ' يؤُلاءِ العربية', 
        labelButtonLogin: ' يؤُلاءِ العربية',
        labelButtonLogout: ' يؤُلاءِ العربية',
        textSignUp: ' يؤُلاءِ العربية',
        labelLinkSignUp: ' يؤُلاءِ العربية',
    },
    register: {
        title: 'Register',
        labelUsername: ' يؤُلاءِ العربية', 
        labelPassword: ' يؤُلاءِ العربية', 
        labelPasswordConfirm: ' يؤُلاءِ العربية( يؤُلاءِ العربية)', 
        descUsername: ['[ يؤُلاءِ العربية] يؤُلاءِ العربية, يؤُلاءِ العربية, يؤُلاءِ العربية(_)', '[ يؤُلاءِ العربية] يؤُلاءِ العربية, يؤُلاءِ العربية يؤُلاءِ العربية', '3 يؤُلاءِ العربية32 يؤُلاءِ العربية'],
        descPassword: ['[ يؤُلاءِ العربية] يؤُلاءِ العربية(@_#$%&!.,+*~\')', '[ يؤُلاءِ العربية] يؤُلاءِ العربية, يؤُلاءِ العربية, يؤُلاءِ العربية, يؤُلاءِ العربية يؤُلاءِ العربية1 يؤُلاءِ العربية', '8 يؤُلاءِ العربية24 يؤُلاءِ العربية'],
        descPasswordConfirm: ' يؤُلاءِ العربية',
        labelButtonConfirm: ' يؤُلاءِ العربية',
        textConfirm: ' يؤُلاءِ العربية',
        labelButtonRegister: ' يؤُلاءِ العربية',
        labelButtonBack: ' يؤُلاءِ العربية',
        textComplete: ' يؤُلاءِ العربية',
        labelButtonLogin: ' يؤُلاءِ العربية',
    },
    formErrorMessages: {
        valueMissing: ' يؤُلاءِ العربية',
        patternMismatch: ' يؤُلاءِ العربية',
        tooLong: ' يؤُلاءِ العربية',
        tooShort: ' يؤُلاءِ العربية',
        passwordIsNotSame: ' يؤُلاءِ العربية',
        isExists: ' يؤُلاءِ العربية',
    },

    dashboard: {
        title: 'Dashboard',
    },
    friends: {
        title: 'Friends',
        labelMatch: ' يؤُلاءِ العربية',
        labelReceiveMatch: ' يؤُلاءِ العربية',
        labelCancel: ' يؤُلاءِ العربية',
        labelRmFriend: ' يؤُلاءِ العربية',
        labelAccept: ' يؤُلاءِ العربية',
        labelDecline: ' يؤُلاءِ العربية',
        labelApply: ' يؤُلاءِ العربية',
        labelSearch: ' يؤُلاءِ العربية',
        labelSendRequest: ' يؤُلاءِ العربية',
        msgNoUsername: ' يؤُلاءِ العربية',
        msgNoFriends: ' يؤُلاءِ العربية',
        labelListFriends: ' يؤُلاءِ العربية',
        labelReceivedRequest: ' يؤُلاءِ العربية',
        labelRecommended: ' يؤُلاءِ العربية',
    },
    lounge: {
        title: 'Lounge',
        labelMatch: ' يؤُلاءِ العربية',
        labelCreateRoom: ' يؤُلاءِ العربية',
        labelDualGame: '2 يؤُلاءِ العربية',
        labelQuadGame: '4 يؤُلاءِ العربية',
        labelCapacity: ' يؤُلاءِ العربية',
        labelAvailable: ' يؤُلاءِ العربية',
        labelWaiting: ' يؤُلاءِ العربية',
    },
    match: {
        title: '',
        labelMatch: ' يؤُلاءِ العربية',
        labelReceiveMatch: ' يؤُلاءِ العربية',
        labelMatchLog: ' يؤُلاءِ العربية',
        labelWins: ' يؤُلاءِ العربية',
        labelLosses: ' يؤُلاءِ العربية',
        fmtWinLoss: '$win يؤُلاءِ العربية  $loss يؤُلاءِ العربية',
    },
    tournament: {
        title: 'Tournament',
        labelCreateTournament: ' يؤُلاءِ العربية',
        labelTournamentTitle: ' يؤُلاءِ العربية',
        labelStart: ' يؤُلاءِ العربية',
        labelEntry: ' يؤُلاءِ العربية',
        labelCancelEntry: ' يؤُلاءِ العربية',
        labelTitleUpcoming: ' يؤُلاءِ العربية',
        labelTitleInPlay: ' يؤُلاءِ العربية',
        labelTitleRecent: ' يؤُلاءِ العربية',
        labelTournamentLog: ' يؤُلاءِ العربية',
    },
    modal: {
        title: '',
        labelNickname: ' يؤُلاءِ العربية',
        labelEntry: ' يؤُلاءِ العربية',
        labelCancel: ' يؤُلاءِ العربية',
        labelAccept: ' يؤُلاءِ العربية',
        labelReject: ' يؤُلاءِ العربية',
        labelCapacity: ' يؤُلاءِ العربية',
        labelAvailable: ' يؤُلاءِ العربية',
        titleSendMatchRequest: ' يؤُلاءِ العربية',
        titleReceiveMatchRequest: ' يؤُلاءِ العربية',
        titleWaitForOpponent: ' يؤُلاءِ العربية...',
        titleEntryTournament:  ' يؤُلاءِ العربية',
    },
    friendRequest: {
        alreadyFriends: '$name يؤُلاءِ العربية',
        usernameNotExists: '$name يؤُلاءِ العربية',
        sendFriendReqSelf: ' يؤُلاءِ العربية',
        invalidDeclineFriendReq: ' يؤُلاءِ العربية',
        sentRequestSuccess: '$name يؤُلاءِ العربية',
        acceptRequestSuccess: '$name يؤُلاءِ العربية',
        declineRequestSuccess: '$name يؤُلاءِ العربية',
        removeSuccess: '$name يؤُلاءِ العربية',
        received: '$name يؤُلاءِ العربية',
        accepted: '$name يؤُلاءِ العربية',
        removed: '$name يؤُلاءِ العربية',
    },
};
const languageLabels = {
    'en': labels_en,
    'ja': labels_ja,
    'fr': labels_fr,
    'la': labels_la,
    'he': labels_he,
    'ar': labels_ar,
};

export const getCurrentLanguageLabels = (lang) => {
    return languageLabels[lang || localStorage.getItem('configLang')] || labels_en;
}

//export const labels = labels_ja;
export const labels = getCurrentLanguageLabels();

export const switchLabels = (lang) => {
    Object.assign(labels, getCurrentLanguageLabels(lang));
};
